image: linogaliana/pocker

before_script:
   - export PATH="/opt/conda/bin:$PATH"

article:
  stage: deploy
  script:
    - Rscript -e "devtools::install_deps()"
    - Rscript ./build.R
    - echo "Rmarkdown compilation worked"
  artifacts:
    paths:
      - html
    when: always
    
