variables:
  GIT_SSL_NO_VERIFY: "1"

before_script:
   - export PATH="/opt/conda/bin:$PATH"
   - Rscript -e "devtools::install_deps()"
   - Rscript -e "install.packages(c('httr', 'openssl', 'roxygen2', 'rsconnect', 'xml2', 'devtools'), dependencies = TRUE)"


pages:
  stage: deploy
  image: git-registry.stable.innovation.insee.eu/w3crk9/pocker
  script:
    - Rscript -e "bookdown::render_book('./index.Rmd', output_dir = 'public')"
  artifacts:
    paths:
      - public
  only:
    - master
