image: rockerextra/python

before_script:
    - apt-get install -y libpython-dev
    - apt-get install -y libpython3-dev

article:
  stage: deploy
  script:
    - Rscript -e "devtools::install_deps()"
    - Rscript ./build.R
  artifacts:
    paths:
      - html
    when: always