article:
  stage: deploy
  image: rocker/verse:3.5.1
  script:
    - apt-get install -y libpython-dev
    - apt-get install -y libpython3-dev
    - Rscript -e "devtools::install_deps()"
    - Rscript ./build.R
  artifacts:
    paths:
      - html
    when: always