on:
  push:
    branches:
      - main
      - master
      - gha

name: bookdown

jobs:
  build:
    runs-on: ubuntu-latest
    container: linogaliana/pocker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          Rscript -e "install.packages(c('remotes','rmarkdown','bookdown'))"
          Rscript -e "devtools::install_deps()"
          Rscript -e "install.packages(c('httr', 'openssl', 'roxygen2', 'rsconnect', 'xml2', 'devtools'), dependencies = TRUE)"
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd", output_dir = "_public")'
      - uses: actions/upload-artifact@v1
        with:
          name: _public
          path: _public/
